//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDUtilitiesLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class domain
    {
        public long domain_id { get; set; }
        public string name { get; set; }
        public string granted_powers { get; set; }
        public string spell_1 { get; set; }
        public string spell_2 { get; set; }
        public string spell_3 { get; set; }
        public string spell_4 { get; set; }
        public string spell_5 { get; set; }
        public string spell_6 { get; set; }
        public string spell_7 { get; set; }
        public string spell_8 { get; set; }
        public string spell_9 { get; set; }
        public string full_text { get; set; }
    }
}
