//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDUtilitiesLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public skill()
        {
            this.skill_subtypes = new HashSet<skill_subtypes>();
            this.classes = new HashSet<@class>();
        }
    
        public long skill_id { get; set; }
        public string name { get; set; }
        public string subtype { get; set; }
        public Nullable<long> key_ability_id { get; set; }
        public string trained { get; set; }
        public string armor_checked { get; set; }
        public string description { get; set; }
        public string spell_check { get; set; }
        public string action { get; set; }
        public string try_again { get; set; }
        public string special { get; set; }
        public string restriction { get; set; }
        public string synergy { get; set; }
        public string epic_use { get; set; }
        public string untrained { get; set; }
        public string full_text { get; set; }
        public string psionic { get; set; }
    
        public virtual ability ability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skill_subtypes> skill_subtypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@class> classes { get; set; }
    }
}
