//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDUtilitiesLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @class()
        {
            this.class_tables = new HashSet<class_tables>();
            this.alignments = new HashSet<alignment>();
            this.skills = new HashSet<skill>();
        }
    
        public long class_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public long hit_die { get; set; }
        public long skill_points { get; set; }
        public Nullable<long> ability_id { get; set; }
        public Nullable<long> type_id { get; set; }
        public string proficiencies { get; set; }
        public Nullable<long> epic_feat_base_level { get; set; }
        public Nullable<long> epic_feat_interval { get; set; }
        public string epic_feat_list { get; set; }
        public string epic_full_text { get; set; }
        public string req_race { get; set; }
        public string req_weapon_proficiency { get; set; }
        public Nullable<long> req_base_attack_bonus { get; set; }
        public string req_skill { get; set; }
        public string req_feat { get; set; }
        public string req_spells { get; set; }
        public string req_languages { get; set; }
        public string req_psionics { get; set; }
        public string req_epic_feat { get; set; }
        public string req_special { get; set; }
        public string spell_list_1 { get; set; }
        public string spell_list_2 { get; set; }
        public string spell_list_3 { get; set; }
        public string spell_list_4 { get; set; }
        public string spell_list_5 { get; set; }
        public string full_text { get; set; }
    
        public virtual ability ability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<class_tables> class_tables { get; set; }
        public virtual spell_types spell_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alignment> alignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skill> skills { get; set; }
    }
}
