//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDUtilitiesLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_tables
    {
        public long class_table_id { get; set; }
        public long class_id { get; set; }
        public long level { get; set; }
        public string base_attack_bonus { get; set; }
        public Nullable<long> fort_save { get; set; }
        public Nullable<long> ref_save { get; set; }
        public Nullable<long> will_save { get; set; }
        public Nullable<long> ac_bonus { get; set; }
        public Nullable<long> flurry_of_blows { get; set; }
        public Nullable<long> unarmored_speed_bonus { get; set; }
        public string unarmed_damage { get; set; }
        public string special { get; set; }
        public Nullable<long> slots_0 { get; set; }
        public Nullable<long> slots_1 { get; set; }
        public Nullable<long> slots_3 { get; set; }
        public Nullable<long> slots_4 { get; set; }
        public Nullable<long> slots_5 { get; set; }
        public Nullable<long> slots_6 { get; set; }
        public Nullable<long> slots_7 { get; set; }
        public Nullable<long> slots_8 { get; set; }
        public Nullable<long> slots_9 { get; set; }
        public Nullable<long> spells_known_0 { get; set; }
        public Nullable<long> spells_known_1 { get; set; }
        public Nullable<long> spells_known_2 { get; set; }
        public Nullable<long> spells_known_3 { get; set; }
        public Nullable<long> spells_known_4 { get; set; }
        public Nullable<long> spells_known_5 { get; set; }
        public Nullable<long> spells_known_6 { get; set; }
        public Nullable<long> spells_known_7 { get; set; }
        public Nullable<long> spells_known_8 { get; set; }
        public Nullable<long> spells_known_9 { get; set; }
        public Nullable<long> slots_2 { get; set; }
    
        public virtual @class @class { get; set; }
    }
}
