//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDUtilitiesLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public long equipment_id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string cost { get; set; }
        public string dmg_s { get; set; }
        public string weight { get; set; }
        public string critical { get; set; }
        public Nullable<long> armor_shield_bonus { get; set; }
        public string dmg_m { get; set; }
        public Nullable<long> maximum_dex_bonus { get; set; }
        public Nullable<long> armor_check_penalty { get; set; }
        public Nullable<long> arcane_spell_failure_chance { get; set; }
        public Nullable<long> range_increment { get; set; }
        public Nullable<long> speed_30 { get; set; }
        public string type { get; set; }
        public Nullable<long> speed_20 { get; set; }
        public string full_text { get; set; }
        public long category_id { get; set; }
        public Nullable<long> subcategory_id { get; set; }
    
        public virtual equipment_category equipment_category { get; set; }
    }
}
