//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDUtilitiesLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class feat
    {
        public long feat_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string multiple { get; set; }
        public string stack { get; set; }
        public string choice { get; set; }
        public string prerequisite { get; set; }
        public string benefit { get; set; }
        public string normal { get; set; }
        public string special { get; set; }
        public string full_text { get; set; }
    }
}
