//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDUtilitiesLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class monster
    {
        public long monster_id { get; set; }
        public long monster_family_Id { get; set; }
        public string name { get; set; }
        public string altname { get; set; }
        public long size_id { get; set; }
        public long type_id { get; set; }
        public Nullable<long> descriptor_id { get; set; }
        public string hit_dice { get; set; }
        public string initiative { get; set; }
        public string speed { get; set; }
        public string armor_class { get; set; }
        public Nullable<long> base_attack { get; set; }
        public Nullable<long> grapple { get; set; }
        public string attack { get; set; }
        public string full_attack { get; set; }
        public string space { get; set; }
        public string reach { get; set; }
        public string special_attacks { get; set; }
        public string special_qualities { get; set; }
        public string saves { get; set; }
        public string abilities { get; set; }
        public string skills { get; set; }
        public string bonus_feats { get; set; }
        public string feats { get; set; }
        public string epic_feats { get; set; }
        public string environment { get; set; }
        public string organization { get; set; }
        public string challenge_rating { get; set; }
        public string treasure { get; set; }
        public string alignment { get; set; }
        public string advancement { get; set; }
        public string level_adjustment { get; set; }
        public string special_abilities { get; set; }
        public string stat_block { get; set; }
        public string full_text { get; set; }
    
        public virtual monster_descriptors monster_descriptors { get; set; }
        public virtual monster_families monster_families { get; set; }
        public virtual monster_sizes monster_sizes { get; set; }
        public virtual monster_types monster_types { get; set; }
    }
}
