//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDUtilitiesLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell
    {
        public long spell_id { get; set; }
        public string name { get; set; }
        public string altname { get; set; }
        public long school_id { get; set; }
        public Nullable<long> subschool_id { get; set; }
        public string descriptor { get; set; }
        public string spellcraft_dc { get; set; }
        public string level { get; set; }
        public string components { get; set; }
        public string casting_time { get; set; }
        public string range { get; set; }
        public string target { get; set; }
        public string area { get; set; }
        public string effect { get; set; }
        public string duration { get; set; }
        public string saving_throw { get; set; }
        public string spell_resistance { get; set; }
        public string short_description { get; set; }
        public string to_develop { get; set; }
        public string material_components { get; set; }
        public string arcane_material_components { get; set; }
        public string focus { get; set; }
        public string description { get; set; }
        public string xp_cost { get; set; }
        public string arcane_focus { get; set; }
        public string wizard_focus { get; set; }
        public string verbal_components { get; set; }
        public string sorcerer_focus { get; set; }
        public string bard_focus { get; set; }
        public string druid_focus { get; set; }
        public string full_text { get; set; }
    
        public virtual spell_schools spell_schools { get; set; }
        public virtual spell_subschools spell_subschools { get; set; }
    }
}
