//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Alignments : DBTable
{
	private int alignment_id
	{
		get;
		set;
	}

	private string name
	{
		get;
		set;
	}

	internal virtual const string TABLE
	{
		get;
		set;
	}

	internal virtual const string FIELD
	{
		get;
		set;
	}

	public virtual Alignments retrieveRecord(int Key)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<NameKey> retrieveAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}

}

