//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Character_classes : DBTable_bridge
{
	private int character_id
	{
		get;
		set;
	}

	private int class_id
	{
		get;
		set;
	}

	public virtual int level
	{
		get;
		set;
	}

	public virtual int caster_level
	{
		get;
		set;
	}

	internal virtual const String FIELD1
	{
		get;
		set;
	}

	internal virtual const String FIELD2
	{
		get;
		set;
	}

	internal virtual const String TABLE
	{
		get;
		set;
	}

	private int deleted
	{
		get;
		set;
	}

	public virtual Characters characters
	{
		get;
		set;
	}

	public virtual Classes Classes
	{
		get;
		set;
	}

	public virtual void delete(int characterKey, int classKey)
	{
		throw new System.NotImplementedException();
	}

	public virtual Domains retrieveRecord(int characterKey, int classKey)
	{
		throw new System.NotImplementedException();
	}

	public virtual void save()
	{
		throw new System.NotImplementedException();
	}

}

