//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Character_abilities : DBTable_bridge
{
	private int character_id
	{
		get;
		set;
	}

	private int ability_id
	{
		get;
		set;
	}

	public virtual int modifier
	{
		get;
		set;
	}

	public virtual int temp
	{
		get;
		set;
	}

	public virtual int temp_modifier
	{
		get;
		set;
	}

	public virtual Abilities Abilities
	{
		get;
		set;
	}

	public virtual Characters Characters
	{
		get;
		set;
	}

}

