//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Characters : DBTable
{
	private int character_id
	{
		get;
		set;
	}

	public virtual string name
	{
		get;
		set;
	}

	public virtual string player_name
	{
		get;
		set;
	}

	public virtual int number_of_classes
	{
		get;
		set;
	}

	private int race_id
	{
		get;
		set;
	}

	private int alignment_id
	{
		get;
		set;
	}

	public virtual string deity
	{
		get;
		set;
	}

	private int size_id
	{
		get;
		set;
	}

	public virtual int age
	{
		get;
		set;
	}

	public virtual string gender
	{
		get;
		set;
	}

	public virtual int height
	{
		get;
		set;
	}

	public virtual int weight
	{
		get;
		set;
	}

	public virtual string eyes
	{
		get;
		set;
	}

	public virtual string hair
	{
		get;
		set;
	}

	public virtual string skin
	{
		get;
		set;
	}

	public virtual string description
	{
		get;
		set;
	}

	internal virtual string FIELD
	{
		get;
		set;
	}

	internal virtual string FIELD_LIST
	{
		get;
		set;
	}

	internal virtual string TABLE
	{
		get;
		set;
	}

	public virtual int experience_points
	{
		get;
		set;
	}

	public virtual int money
	{
		get;
		set;
	}

	public virtual Alignments Alignments
	{
		get;
		set;
	}

	public virtual Races races
	{
		get;
		set;
	}

	public virtual void delete()
	{
		throw new System.NotImplementedException();
	}

	public virtual Domains retrieveRecord(int Key)
	{
		throw new System.NotImplementedException();
	}

	public virtual void save()
	{
		throw new System.NotImplementedException();
	}

	public virtual void runSqlite(string Sql, string s1, string s2, int i1, int i2, int i3, string s3, int i4, string s4, int i5, int i6, string s5, string s6, string s7, string s8, int i7)
	{
		throw new System.NotImplementedException();
	}

}

