//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Character_hit_points : DBTable_lookup
{
	private int character_id
	{
		get;
		set;
	}

	private int level
	{
		get;
		set;
	}

	public virtual int amount
	{
		get;
		set;
	}

	public virtual Characters Characters
	{
		get;
		set;
	}

}

