//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Class_skills : DBTable
{
	private int class_id
	{
		get;
		set;
	}

	private int skill_id
	{
		get;
		set;
	}

	public virtual Classes classes
	{
		get;
		set;
	}

	public virtual Skills skills
	{
		get;
		set;
	}

}

