//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DBTable_bridge : DBTable
{
	public override void Delete(string table, string field1, string field2, int key1, int key2)
	{
		throw new System.NotImplementedException();
	}

}

