//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DBTable
{
	private string connection
	{
		get;
		set;
	}

	public virtual void Save(string Table, object Key, List<String> FieldList)
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete(string Table, int Key)
	{
		throw new System.NotImplementedException();
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}

}

