//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Equipment_category
{
	private int category_id
	{
		get;
		set;
	}

	public virtual string category
	{
		get;
		set;
	}

	internal virtual const String FIELD
	{
		get;
		set;
	}

	internal virtual const String FIELD_LIST
	{
		get;
		set;
	}

	internal virtual const String TABLE
	{
		get;
		set;
	}

	public virtual void delete(int Key)
	{
		throw new System.NotImplementedException();
	}

	public virtual Equipment_category retrieve(int Key)
	{
		throw new System.NotImplementedException();
	}

	public virtual void save(int Key)
	{
		throw new System.NotImplementedException();
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}

}

