//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Equipment_category
{
	private int category_id
	{
		get;
		set;
	}

	public virtual string category
	{
		get;
		set;
	}

}

