//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Items : DBTable
{
	private int item_id
	{
		get;
		set;
	}

	public virtual string name
	{
		get;
		set;
	}

	public virtual string category
	{
		get;
		set;
	}

	public virtual string subcategory
	{
		get;
		set;
	}

	public virtual string special_ability
	{
		get;
		set;
	}

	public virtual string aura
	{
		get;
		set;
	}

	public virtual int caster_level
	{
		get;
		set;
	}

	public virtual string price
	{
		get;
		set;
	}

	public virtual int manifester_level
	{
		get;
		set;
	}

	public virtual string prerequisite
	{
		get;
		set;
	}

	public virtual string cost
	{
		get;
		set;
	}

	public virtual string weight
	{
		get;
		set;
	}

	public virtual string full_text
	{
		get;
		set;
	}

	internal virtual const String FIELD
	{
		get;
		set;
	}

	internal virtual const String FIELD_LIST
	{
		get;
		set;
	}

	internal virtual const String TABLE
	{
		get;
		set;
	}

	public virtual void delete(int Key)
	{
		throw new System.NotImplementedException();
	}

	public virtual Items retrieve(int Key)
	{
		throw new System.NotImplementedException();
	}

	public virtual void save(int Key)
	{
		throw new System.NotImplementedException();
	}

	public override string ToString()
	{
		throw new System.NotImplementedException();
	}

}

