//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Monster_sizes : DBTable
{
	private int size_id
	{
		get;
		set;
	}

	public virtual string size
	{
		get;
		set;
	}

	private List<String> fieldList
	{
		get;
		set;
	}

	internal virtual const String FIELD
	{
		get;
		set;
	}

	internal virtual const String FIELD_LIST
	{
		get;
		set;
	}

	internal virtual const String TABLE
	{
		get;
		set;
	}

	public virtual Monsters monsters
	{
		get;
		set;
	}

	public virtual void delete(int Key)
	{
		throw new System.NotImplementedException();
	}

	public virtual Monster_sizes retrieve(int Key)
	{
		throw new System.NotImplementedException();
	}

	public virtual void save(int Key)
	{
		throw new System.NotImplementedException();
	}

	public override string ToString()
	{
		throw new System.NotImplementedException();
	}

}

