//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NameKey
{
	private string name
	{
		get;
		set;
	}

	private int Key
	{
		get;
		set;
	}

	public virtual void ToSring()
	{
		throw new System.NotImplementedException();
	}

}

