//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Power-subdisciplines : DBTable
{
	private int subdiscipline_id
	{
		get;
		set;
	}

	public virtual string subdiscipline
	{
		get;
		set;
	}

	public virtual Powers powers
	{
		get;
		set;
	}

}

