//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Skill_subtypes : DBTable
{
	private int subtype_id
	{
		get;
		set;
	}

	public virtual string subtype
	{
		get;
		set;
	}

	private int skill_id
	{
		get;
		set;
	}

}

