//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Spell_subschools : DBTable
{
	private int subschool_id
	{
		get;
		set;
	}

	public virtual string subschool
	{
		get;
		set;
	}

}

